name: LaTeX Build

on:
  push:
    branches:
      - main  # or 'master' or any branch you want to trigger the action
  pull_request:
    branches:
      - main  # optional, if you also want to build on PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up TeX Live
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra

    - name: Compile LaTeX document
      working-directory: ./lectures/day_1_intro_to_mems
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error intro_to_course.tex
        pdflatex -interaction=nonstopmode -halt-on-error intro_to_course.tex  # Run twice for cross-references

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: lectures/day_1_intro_to_mems/intro_to_course.pdf

    - name: Commit and push the PDF
      env:
        ACTIONS_PAT_NEW: ${{ secrets.ACTIONS_PAT_NEW }}  # Use the PAT from the secrets
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add lectures/day_1_intro_to_mems/intro_to_course.pdf
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-build PDF from LaTeX"
        git push https://x-access-token:${{ secrets.ACTIONS_PAT_NEW }}@github.com/${{ github.repository }}.git HEAD:main
