name: LaTeX Build

on:
  push:
    branches:
      - main  # or 'master' or any branch you want to trigger the action
  pull_request:
    branches:
      - main  # optional, if you also want to build on PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up TeX Live
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra

    - name: Compile LaTeX documents
      run: |
        find ./lectures -name "*.tex" | while read file; do
          pdflatex -interaction=nonstopmode -halt-on-error "$file"
          pdflatex -interaction=nonstopmode -halt-on-error "$file"  # Run twice for cross-references
        done

    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdfs
        path: '**/*.pdf'  # Upload all PDFs generated in any subfolder

    - name: Commit and push the PDFs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the PAT from the secrets
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        find ./lectures -name "*.pdf" | while read pdf; do
          git add "$pdf"
        done
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-build PDFs from LaTeX"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
